import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/Header";


export const metadata: Metadata = {
  title: "Lingua-uz",
  description: "Generated by Nurkhon",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
            <Header />
            {children}
        </main>
      </body>
    </html>
  );
}
